file_name: './datasets/example/geo.csv'
specimen: 'id'   #"Please enter the name of the colum containing the specimens names: "
names: ['id', 'ALLSKY_SFC_SW_DWN', 'T2M', 'PRECTOTCORR', 'QV2M', 'WS10M']
bootstrap_threshold: 0
dist_threshold: 60
window_size: 200
step_size: 100
bootstrap_amount: 100
data_names: ['ALLSKY_SFC_SW_DWN_newick', 'T2M_newick', 'QV2M_newick', 'PRECTOTCORR_newick', 'WS10M_newick']
reference_gene_dir: './datasets/example'
reference_gene_file: 'sequences.fasta'
makeDebugFiles: True
alignment_method: '1' #Please enter 1 for pairwise2 alignment or 2 for pymuscle5
distance_method: '2' #Please enter 1 for Least-Square distance or 2 for Robinson-Foulds
fit_method: '2' # 1:Wider Fit by elongating with Gap (starAlignment), 2:Narrow-fit prevent elongation with gap when possible
tree_type: '2' # 1: BioPython consensus tree, 2: FastTree application
